config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#index"
  resources :users, only: %i[new create]
  resources :posts, only: %i[index new create show destroy]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :writer, presence: true
  validates :main_text_detail, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :posts # Userが複数の投稿を持つ関連付け

  validates :password, length: { minimum: 8, maximum: 20 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password, format: { with: /(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_])/, message: "は大文字、小文字、数字、特殊文字を含める必要があります" }, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true

  validate :no_consecutive_characters

  private

  def no_consecutive_characters
    if password =~ /(.)\1\1/
      errors.add(:password, "は同じ文字を3回以上続けて使用することはできません")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [ :new, :create ]

  def index
    @posts = Post.includes(:user).page(params[:page]).per(8)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: "投稿を作成しました"
    else
      flash.now[:danger] = t("投稿を作成出来ませんでした")
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "投稿を更新しました"
    else
      flash.now[:danger] = "投稿を更新出来ませんでした"
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: "投稿を削除しました"
  end

  private

  def post_params
    params.require(:post).permit(:title, :writer, :main_text_detail, :body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top index]

  def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # 成功した場合、アプリケーションのルートにリダイレクト
      redirect_to root_path, notice: "ユーザー登録が完了しました"
    else
      # エラーをコンソールに出力
      puts @user.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Myapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <script src="https://unpkg.com/heroicons@2.0.16/dist/heroicons.min.js"></script>
  </head>

  <body>
    <% if logged_in? %>
      <%= render "shared/header" %>
    <% else %>
      <%= render "shared/before_login_header" %>
    <% end %>
    <!-- コンテンツエリア -->
    <div class="content">
      <!-- ここにメニューやページごとのコンテンツが入る -->
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="post-id-<%= post.id %>">
    <div class="card">
      <div class="card-body">
        <div class="d-flex">
          <!-- 他の投稿に関連する内容をここに追加 -->
          <h4 class="card-title">
            <%= link_to post.main_text_detail, post_path(post) %>
          </h4>
          <div class="ms-auto">
            <!-- ログインしている場合 -->
            <% if current_user %>
              <!-- 投稿者の場合 -->
              <% if post.user_id == current_user.id %>
                </svg>
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" class="h-5 w-5 text-red-500" viewBox="0 0 20 20" fill="currentColor">
                  <%= link_to post_path(post), id: "button-delete-#{post.id}", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } do %>
                    <path fill-rule="evenodd" d="M5 4h10l1 1h3v1H3V5h3l1-1zm0 2v10h10V6H5z" clip-rule="evenodd"/>
                  <% end %>
                </svg>
                <!-- 投稿者のみに編集ボタンを表示 -->
                <%= link_to edit_post_path(post), class: "btn btn-sm btn-warning" do %>
                  編集
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>投稿を編集</h1>

<%= form_with(model: @post, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :main_text_detail, "メインテキスト詳細" %>
    <%= form.text_area :main_text_detail, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body, "本文" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "更新", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <!-- メッセージ表示エリア -->
  <div class="alert-container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
  </div>
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @posts.present? %>
          <%= render @posts %>
        <% else %>
          <div class="mb-3">掲示板がありません</div>
        <% end %>
      </div>
    </div>
  </div>
  <!-- ログインしている場合のみ「新規投稿」ボタンを表示 -->
  <% if logged_in? %>
    <div class="input-group-append">
      <%= link_to t("新規投稿"), new_post_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>
<%= paginate @posts %>

app/views/posts/new.html.erb
<div class="container">
  <!-- メッセージ表示エリア -->
  <div class="alert-container">
    <% if flash.now[:danger] %>
      <div class="alert alert-danger">
        <%= flash.now[:danger] %>
      </div>
    <% end %>
    <% if @post.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <!-- 投稿フォーム -->
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t("投稿") %></h1>
      <%= form_with model: @post, class: "new_post" do |f| %>
        <div class="mb-3">
          <%= f.label :title, "書名" %>
          <%= f.text_field :title %>
        </div>
        <div class="mb-3">
          <%= f.label :writer, "著者名" %>
          <%= f.text_field :writer %>
        </div>
        <div class="mb-3">
          <%= f.label :main_text_detail, "本文詳細" %>
          <%= f.text_area :main_text_detail %>
        </div>
        <div class="mb-3">
          <%= f.label :body, "感想（任意）" %>
          <%= f.text_area :body, required: false %>
        </div>
        <%= f.submit "投稿", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.writer %></p>
<p><%= @post.main_text_detail %></p>
<p><%= @post.body %></p>
<div class="ms-auto">
  <!-- ログインしている場合 -->
  <% if current_user %>
    <!-- 投稿者の場合 -->
    <% if @post.user_id == current_user.id %>
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" class="h-5 w-5 text-red-500" viewBox="0 0 20 20" fill="currentColor">
        <%= link_to post_path(@post), id: "button-delete-#{@post.id}", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } do %>
          <path fill-rule="evenodd" d="M5 4h10l1 1h3v1H3V5h3l1-1zm0 2v10h10V6H5z" clip-rule="evenodd"/>
        <% end %>
      </svg>
    <% end %>
  <% end %>
</div>

app/views/shared/_before_login_header.html.erb
<header class="">
  <nav class="">
    <!-- ロゴ -->
    <div class="logo">
      <a class="" href="/">Book_quarter</a>
    </div>
    <!-- ナビゲーションリンクを右揃え -->
    <div class="">
      <%= link_to "投稿一覧", posts_path, class: "" %>
      <%= link_to "ログイン", login_path, class: "" %>
    </div>
  </nav>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="<%= flash_background_color(message_type) %> px-4 py-2 rounded-md text-white mb-4">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="right-0">
  <nav class="">
    <!-- ナビゲーションリンクを右揃え -->
    <div class="">
      <%= link_to "利用規約", "#", class: "" %>
      <%= link_to "プライバシーポリシー", "#", class: "font-bold hover:bg-gray" %>
    </div>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header class="bg-thin-orange h-72px top-0 left-0">
  <nav class="flex justify-between items-center">
    <!-- ロゴ -->
    <div class="logo">
      <a class="" href="/">Book_quarter</a>
    </div>
    <!-- ナビゲーションリンクを右揃え -->
    <div class="">
      <%= link_to "投稿一覧", posts_path, class: "" %>
      <%# <%= link_to "ブックマーク", "#", class: "" %>
      <%= link_to "ログアウト", logout_path, class: "", data: { turbo_method: :delete } %>
    </div>
  </nav>
</header>

app/views/shared/_posts.html.erb
<!-- @ postsをループで回して各postを扱う -->
<% @posts.each do |post| %>
  <div class="col-sm-12 col-lg-4 mb-3">
    <div id="post-id-<%= post.id %>">
      <div class="card">
        <%= image_tag "post_placeholder.png", class: "card-img-top", width: "300", height:"200" %>
        <div class="card-body">
          <div class="d-flex">
            <!-- 他の投稿に関連する内容をここに追加 -->
            <h4 class="card-title">
              <%= link_to post.title, '#' %>
            </h4>
            <div class='ms-auto'>
              <%= link_to '#', id: 'button-edit-#{post.id}' do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-blue-500" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M17.414 2.586a2 2 0 00-2.828 0l-10 10V16h3.414l10-10a2 2 0 000-2.828zM15 5l-3 3-3-3L12 2l3 3z"/>
                </svg>
              <% end %>
              <%= link_to '#', id: 'button-delete-#{board.id}', method: :delete, data: {confirm: ''} do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-red-500" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M5 4h10l1 1h3v1H3V5h3l1-1zm0 2v10h10V6H5z" clip-rule="evenodd"/>
                </svg>
              <% end %>
            </div>
          </div>
          <ul class="list-inline">
            <li><i class="bi bi-person"></i><%= post.user.decorate.full_name %></li>
            <li><i class="bi bi-calendar"></i><%= l post.created_at, format: :short %></li>
          </ul>
          <p class="card-text"><%= post.body %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>  <!-- ループ終了 -->

app/views/static_pages/index.html.erb
<div class="bg-thin-orange h-72px top-0 left-0">
  <!-- メッセージ表示エリア -->
  <div class="alert-container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
  </div>
  <div class="top-inner-text">
    <h1 class="", style="width: 430px">タイトルや説明など（仮）</h1>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class="">
      <h1>ログイン</h1>
      <%= form_with url: login_path do |f| %>
        <div class="mb-3">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <%= f.submit "ログイン", class: "btn btn-primary" %>
      <% end %>
      <div class="">
        <%= link_to "新規登録ページへ", new_user_path, class: "" %>
        <%# <%= link_to "パスワードをお忘れの方はこちら", "#", class: "" %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <!-- エラーメッセージ -->
    <% if @user.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">エラーが発生しました:</h4>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="">
      <h1>ユーザー登録</h1>
      <!-- ユーザー登録フォーム -->
      <%= form_with model: @user do |f| %>
        <div class="mb-3">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "form-label" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <%= f.submit "登録", class: "btn btn-primary" %>
      <% end %>
      <div class="text-center">
        <%= link_to "ログインページへ", login_path, class: "" %>
      </div>
    </div>
  </div>
</div>